In [1]:
# Data Frame Python list 
import pandas as pd

In [3]:
list= [ 
    ["sunil" ,55],
    ["Rohan", 41],
    ["Afreen",7]
]

In [5]:
pd.DataFrame(list,columns=["Name", "Rollno"])

     Name  Rollno
0   sunil      55
1   Rohan      41
2  Afreen       7

In [6]:
data= {
    "A": [33,22,33,],
    "B": [23,12,39,],
    "C": [33,22,3,],
    "D": [33,20,30,]
}
pd.DataFrame(data)

    A   B   C   D
0  33  23  33  33
1  22  12  22  20
2  33  39   3  30