In [67]:
from sklearn.model_selection import StratifiedShuffleSplit
import pandas as pd
import numpy as np

In [68]:
df= pd.read_csv("housing.csv")

In [69]:
split = StratifiedShuffleSplit(n_splits=1,test_size=0.1,random_state=42)
for train_index,test_index in split.split(df,df["ocean_proximity"]):
    train_set=df.iloc[train_index]
    test_set=df.iloc[test_index]
# train_set
# test_set

In [70]:
housing=   train_set.drop("median_house_value",axis=1)
housing_lables=  test_set["median_house_value"]

In [71]:
# We use option 3 by using Simple Imputer 
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(strategy="median")
housing= housing.select_dtypes(include=[np.number])
imputer.fit(housing)
housing["ocean_proximity"]= train_set["ocean_proximity"]

In [72]:
# now we are going to encode by ONE Hot Encoder 
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
housing["ocean_proximity"]= train_set["ocean_proximity"]
housing_cat= housing[["ocean_proximity"]]           # work on ocean proximity 
housing_cat_hot_encoded= onehotencoder.fit_transform(housing_cat)
housing_cat_hot_encoded.toarray()
housing_cat_df= pd.DataFrame(housing_cat_hot_encoded.toarray(),columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index= housing.index)

housing=housing.drop("ocean_proximity",axis=1)
housing = pd.concat([housing, housing_cat_df],axis=1)

In [86]:
#  now we are going to sacle the large value to small value for fast process data
# we have 2 way to solve this problem 
 # 1---> MinMaxScaler        2------> StandardScaler

# 1 MinMaxScaler   
     # scaled_value= (x-min)/(max-min)

from sklearn.preprocessing import MinMaxScaler 
scaler= MinMaxScaler(feature_range=(-1,1))
housing_scale_minmax= scaler.fit_transform(housing)
housing_scale_minmax_df= pd.DataFrame(housing_scale_minmax,columns=housing.columns,index= housing.index)
housing_scale_minmax_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
10553,0.322709,-0.766206,-0.490196,-0.850486,-0.890113,-0.927689,-0.890461,0.049792,1.0,-1.0,-1.0,-1.0,-1.0
15125,0.492032,-0.929862,-0.372549,-0.705296,-0.714729,-0.852743,-0.723355,-0.372078,1.0,-1.0,-1.0,-1.0,-1.0
12905,-0.398406,0.290117,-0.215686,-0.875515,-0.839826,-0.925839,-0.834539,-0.695452,-1.0,1.0,-1.0,-1.0,-1.0
6453,0.252988,-0.664187,-0.058824,-0.802360,-0.737389,-0.896578,-0.750987,-0.563592,-1.0,1.0,-1.0,-1.0,-1.0
15251,0.410359,-0.906482,-0.372549,-0.906039,-0.878938,-0.980493,-0.932237,-0.341485,-1.0,-1.0,-1.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14439,0.416335,-0.944740,0.137255,-0.902783,-0.857209,-0.953754,-0.856908,-0.728666,-1.0,-1.0,-1.0,-1.0,1.0
17958,-0.527888,0.018066,0.333333,-0.903291,-0.899426,-0.949046,-0.897697,-0.247348,1.0,-1.0,-1.0,-1.0,-1.0
9470,-0.888446,0.466525,-0.411765,-0.897695,-0.869316,-0.934191,-0.864474,-0.625219,1.0,-1.0,-1.0,-1.0,-1.0
19164,-0.669323,0.232731,-0.411765,-0.914687,-0.894770,-0.950839,-0.893092,-0.615757,1.0,-1.0,-1.0,-1.0,-1.0
20249,0.015936,-0.645058,-0.568627,-0.226993,-0.250039,-0.600381,-0.260197,-0.286120,-1.0,-1.0,-1.0,-1.0,1.0

In [87]:
# way 2 in case of wrong data we 

# 2---> StandardSacler()
from sklearn.preprocessing import StandardScaler
Sscaler= StandardScaler()
housing_standard= Sscaler.fit_transform(housing)
housing_standard_df= pd.DataFrame(housing_standard,columns=housing.columns,index= housing.index)
housing_standard_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
10553,0.932454,-0.934628,-1.167228,0.147201,-0.434038,-0.115613,-0.433191,2.243346,1.122187,-0.681898,-0.016408,-0.353264,-0.384448
15125,1.357073,-1.294713,-0.928799,1.469467,0.925703,1.069167,0.913538,0.627606,1.122187,-0.681898,-0.016408,-0.353264,-0.384448
12905,-0.875920,1.389556,-0.610895,-0.080744,-0.044165,-0.086370,0.017486,-0.610902,-0.891117,1.466496,-0.016408,-0.353264,-0.384448
6453,0.757612,-0.710160,-0.292991,0.585486,0.750020,0.376199,0.690850,-0.105884,-0.891117,1.466496,-0.016408,-0.353264,-0.384448
15251,1.152257,-1.243273,-0.928799,-0.358725,-0.347399,-0.950365,-0.769873,0.744775,-0.891117,-0.681898,-0.016408,-0.353264,2.601132
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14439,1.167243,-1.327448,0.104389,-0.329074,-0.178936,-0.527672,-0.162785,-0.738108,-0.891117,-0.681898,-0.016408,-0.353264,2.601132
17958,-1.200628,0.790974,0.501770,-0.333707,-0.506236,-0.453236,-0.491514,1.105313,1.122187,-0.681898,-0.016408,-0.353264,-0.384448
9470,-2.104815,1.777700,-1.008275,-0.282744,-0.272794,-0.218407,-0.223759,-0.341912,1.122187,-0.681898,-0.016408,-0.353264,-0.384448
19164,-1.555309,1.263293,-1.008275,-0.437487,-0.470137,-0.481593,-0.454399,-0.305673,1.122187,-0.681898,-0.016408,-0.353264,-0.384448
20249,0.163146,-0.668072,-1.326180,5.825440,4.528414,5.058608,4.646203,0.956819,-0.891117,-0.681898,-0.016408,-0.353264,2.601132