In [53]:
from sklearn.model_selection import StratifiedShuffleSplit
import pandas as pd
import numpy as np

In [54]:
df= pd.read_csv("housing.csv")

In [55]:
split = StratifiedShuffleSplit(n_splits=1,test_size=0.1,random_state=42)
for train_index,test_index in split.split(df,df["ocean_proximity"]):
    train_set=df.iloc[train_index]
    test_set=df.iloc[test_index]
# train_set
# test_set

In [56]:
housing=   train_set.drop("median_house_value",axis=1)
housing_lables=  test_set["median_house_value"]

In [57]:
housing= housing.drop("ocean_proximity",axis=1)
housing
demo=train_set.drop("ocean_proximity",axis=1)
demo

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10553,-117.71,33.64,14.0,2945.0,356.0,1293.0,335.0,8.1110,308900.0
15125,-116.86,32.87,17.0,5799.0,921.0,2630.0,843.0,5.0524,285400.0
12905,-121.33,38.61,21.0,2453.0,518.0,1326.0,505.0,2.7079,148000.0
6453,-118.06,34.12,25.0,3891.0,848.0,1848.0,759.0,3.6639,248100.0
15251,-117.27,32.98,17.0,1853.0,392.0,351.0,208.0,5.2742,230700.0
...,...,...,...,...,...,...,...,...,...
14439,-117.24,32.80,30.0,1917.0,462.0,828.0,437.0,2.4671,276300.0
17958,-121.98,37.33,35.0,1907.0,326.0,912.0,313.0,5.9567,294300.0
9470,-123.79,39.44,16.0,2017.0,423.0,1177.0,414.0,3.2171,116200.0
19164,-122.69,38.34,16.0,1683.0,341.0,880.0,327.0,3.2857,160200.0
20249,-119.25,34.21,12.0,15201.0,2418.0,7132.0,2251.0,5.6756,301800.0

In [58]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [59]:
mypipeline = Pipeline([
          ("impute",SimpleImputer(strategy='median')),
           ("scale",StandardScaler())
            
           ])

In [77]:
housing=mypipeline.fit_transform(housing)
demo=train_set.drop("ocean_proximity",axis=1)
demo = demo.drop("median_house_value",axis=1)
# demo
housing_df= pd.DataFrame(housing,columns=demo.columns,index=demo.index)
housing_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
10553,0.932454,-0.934628,-1.167228,0.147201,-0.433631,-0.115613,-0.433191,2.243346
15125,1.357073,-1.294713,-0.928799,1.469467,0.932772,1.069167,0.913538,0.627606
12905,-0.875920,1.389556,-0.610895,-0.080744,-0.041848,-0.086370,0.017486,-0.610902
6453,0.757612,-0.710160,-0.292991,0.585486,0.756228,0.376199,0.690850,-0.105884
15251,1.152257,-1.243273,-0.928799,-0.358725,-0.346568,-0.950365,-0.769873,0.744775
...,...,...,...,...,...,...,...,...
14439,1.167243,-1.327448,0.104389,-0.329074,-0.177279,-0.527672,-0.162785,-0.738108
17958,-1.200628,0.790974,0.501770,-0.333707,-0.506183,-0.453236,-0.491514,1.105313
9470,-2.104815,1.777700,-1.008275,-0.282744,-0.271597,-0.218407,-0.223759,-0.341912
19164,-1.555309,1.263293,-1.008275,-0.437487,-0.469907,-0.481593,-0.454399,-0.305673
20249,0.163146,-0.668072,-1.326180,5.825440,4.553134,5.058608,4.646203,0.956819